apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gobg
  name: gobg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobg
  strategy: {}
  template:
    metadata:
      labels:
        app: gobg
    spec:
      containers:
      - image: ghcr.io/christianh814/gobg:v1.3.3
        name: gobg
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gobg
  name: gobg
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gobg
  type: LoadBalancer
