apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
          annotations:
            analysis: kargo-demo
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: grycap/cowsay
                imagePullPolicy: IfNotPresent
              restartPolicy: Never
