---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: default-promote
  namespace: kargo-demo
spec:
  vars:
  - name: repoURL
    value: https://github.com/christianh814/ak-containers-from-the-couch
  - name: sourceBranch
    value: main
  - name: imageRepo
    value: docker.io/christianh814/gobg
  - name: targetBranch

  steps:

  - uses: git-clone
    as: clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.sourceBranch }}
        path: ./src
      - branch: stage/${{ vars.targetBranch }}
        create: true
        path: ./dst

  - uses: git-clear
    as: clear
    config:
      path: ./dst

  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/app/stages/${{ vars.targetBranch }}
      images:
      - image: ${{ vars.imageRepo }}
        tag: ${{ imageFrom( vars.imageRepo ).Tag }}

  - uses: git-commit
    as: commit-main
    config:
      path: ./src
      message: ${{ task.outputs['update-image'].commitMessage }}

  - uses: git-push
    as: push-main
    config:
      path: ./src
      targetBranch: ${{ vars.sourceBranch }}

  - uses: kustomize-build
    as: build-manifests
    config:
      path: ./src/app/stages/${{ vars.targetBranch }}
      outPath: ./dst/${{ vars.targetBranch }}.yaml

  - uses: git-commit
    as: commit
    config:
      path: ./dst
      message: ${{ task.outputs['update-image'].commitMessage }}

  - uses: git-push
    as: push
    config:
      path: ./dst
      targetBranch: stage/${{ vars.targetBranch }}

  - uses: argocd-update
    as: sync-argocd
    config:
      apps:
      - name: kargo-demo-${{ vars.targetBranch }}
        namespace: argocd
        sources:
        - repoURL: ${{ vars.repoURL }}
          desiredRevision: ${{ task.outputs.commit.commit }}
