---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: green
    argocd.argoproj.io/sync-wave: "4"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: targetBranch
        value: prod
      steps:
      - task:
          name: default-promote
        as: promote-to-prod
