apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  metrics:
  - name: catfact
    successCondition: result >= 0
    provider:
      web:
        url: "https://catfact.ninja/fact"
        jsonPath: "{$.length}"
