apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: kargo-demo-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/christianh814/kargo-deployment-example
        targetRevision: stage/{{stage}}
        path: ./
      destination:
        name: eks-{{stage}
        namespace: demo
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
