apiVersion: v1
kind: Service
metadata:
  labels:
    app: gobg
  name: gobg
spec:
  type: LoadBalancer # For EKS
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gobg
